from aiogram import types

keyboard = types.InlineKeyboardMarkup(1)
mailing = types.InlineKeyboardButton('Рассылка', callback_data='mailing')
statistics = types.InlineKeyboardButton('Статистика', callback_data='statistics')
prices = types.InlineKeyboardButton('Изменить цены', callback_data='update_prices')
update_qiwi = types.InlineKeyboardButton('Изменить QIWI', callback_data='update_qiwi')
update_yoo = types.InlineKeyboardButton('Изменить YOOMONEY', callback_data='update_yoo')
update_help_link = types.InlineKeyboardButton('Изменить аккаунт ТП', callback_data='update_help_link')
update_referal_percentage = types.InlineKeyboardButton('Изменить процент рефералов', callback_data='update_percentage')
show_referals = types.InlineKeyboardButton('Рефералы', callback_data='show_referals')
edit_referals = types.InlineKeyboardButton('Изменить процент реферала', callback_data='update_percentage_ind')
update_channel_link = types.InlineKeyboardButton('Изменить ссылку на канал', callback_data='update_channel_link')
add_admin = types.InlineKeyboardButton('Добавить админа', callback_data='add_admin')
remove_admin = types.InlineKeyboardButton('Удалить админа', callback_data='remove_admin')
switch_subscription_check = types.InlineKeyboardButton('Включить/Выключить проверку на подписку', callback_data='switch_subscription_check')
qiwi_balance = types.InlineKeyboardButton('Баланс QIWI', callback_data='qiwi_balance')
keyboard.add(mailing, statistics, prices)
keyboard.row(update_qiwi, update_yoo)
keyboard.add(update_help_link, update_referal_percentage, show_referals, edit_referals, add_admin, remove_admin, update_channel_link, switch_subscription_check, qiwi_balance)